config/routes.rb
Rails.application.routes.draw do
  get 'votes/new'
  get 'votes/create'
  get 'votes/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'articles#index'
  resources :users, only: [:index, :create, :new, :show]
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles, only: [:new, :create, :destroy, :show]
  resources :categories, only: [:show]
  resources :votes, only: [ :create, :destroy]
  # get 'logout', to: 'sessions#destroy', as: 'logout'
  # get 'new_login', to: 'sessions#new', as: 'new_login'
  # post 'login', to: 'sessions#create', as: 'login'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { in: (3..30) }
  validates :body, presence: true, length: { in: (15..2000) }
  validates :categories, presence: true

  belongs_to :author, class_name: 'User'
  has_and_belongs_to_many :categories
  has_many :votes, dependent: :destroy

  accepts_nested_attributes_for :categories, reject_if: :all_blank, allow_destroy: true
  has_one_attached :image
  has_rich_text :body
  validates :image, presence: true
end

app/models/articles_category.rb
class ArticlesCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, uniqueness: true, length: { in: (3..10) }
  has_many :authored_articles, class_name: 'Article', foreign_key: :author_id, dependent: :destroy
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  private

  def sign_in
    redirect_to new_session_path unless current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :sign_in

  def index
    @category = Category.includes(:articles).order(priority: :desc)
    @category_article = @category.map { |c| [c, c.articles.order(created_at: :desc).first] }
    @most_popular = most_popular[0]
  end

  def show
    @article = Article.where('id = ?', params[:id]).includes(:author, :votes).first
  end

  def new
    @article = current_user.authored_articles.new
    @article.categories.new
  end

  def create
    @article = current_user.authored_articles.new article_params

    if @article.save
      redirect_to root_path,
                  notice: 'Article successfully created'
    else
      render :new,
             alert: 'Please check the form and re-submit'
    end
  end

  private

  def most_popular
    @article_hash = Vote.includes(:article).group(:article).count
    if @article_hash.empty?
      [Article.first, nil]
    else
      @article_hash.max_by { |_article, article_counts| article_counts }
    end
  end

  def article_params
    params.require(:article).permit(:title, :body, :image, category_ids: [],
                                                           categories_attributes: %i[id name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :sign_in

  def show
    @category = Category.find(params[:id])
    @articles = @category.articles.order(created_at: :desc).includes(:author, :votes)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(name: params[:name])
    if @user
      session[:user_id] = @user.id
      redirect_to root_path,
                  notice: "Welcome #{current_user.name}\n You have successfully signed in"
    else
      flash[:alert] = 'Please Enter a valid name'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path,
                notice: 'You have successfully Log out'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :sign_in, except: %i[new create]

  def index; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path,
                  notice: "Welcome #{current_user.name}\n Your Account is Ready"
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    @authored_articles = current_user.authored_articles.includes(:categories, :author, :votes)
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :sign_in
  before_action :set_article

  def create
    @vote = Vote.new(article_id: params[:article_id], user_id: current_user.id)
    @article = Article.find(params[:article_id])
    if @vote.save
      @article.categories = @article.categories.map do |category|
        category.priority += 1
        category.save
        category
      end
      redirect_to @article,
                  notice: 'Thanks for your vote'
    else
      redirect_to root_path,
                  alert: 'Something went wrong\n Please vote again'
    end
  end

  def destroy
    @vote = Vote.find_by(article_id: params[:article_id], user_id: current_user.id)
    @article = Article.find(params[:article_id])
    if @vote&.destroy
      @article.categories = @article.categories.map do |category|
        category.priority -= 1
        category.save
        category
      end
      redirect_to @article,
                  notice: 'You can vote again'
    else
      redirect_to @article,
                  alert: "Can't Downvote article if you have not Upvoted"
    end
  end

  private

  def set_article
    redirect_to new_article_path unless Article.count.positive?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_notice()
    if notice
      'shared/notice'
    else
      'shared/empty'
    end
  end

  def flash_alert()
    if alert
      'shared/alert'
    else
      'shared/empty'
    end
  end

  def signed_in_details()
    if current_user
      'layouts/signed_in_details'
    else
      'shared/empty'
    end
  end

  def signed_out_details()
    if current_user.nil?
      'layouts/signed_out_details'
    else
      'shared/empty'
    end
  end

  def upvote_or_downvote(article)
    @vote = Vote.find_by(article: article, user: current_user)
    if @vote
      link_to 'Downvote', vote_path(article_id: article.id, category_id: params[:id]),
              method: :delete,
              class: 'btn btn-danger'
    else
      link_to 'Upvote', votes_path(article_id: article.id, category_id: params[:id]),
              method: :post,
              class: 'btn btn-success'
    end
  end

  def truncate_or_not(article)
    if article.body.to_plain_text.length > 120
      article.body.to_plain_text.truncate(120)
    else
      article.body
    end
  end

  def continue_reading(article)
    link_to 'continue reading', article, class: 'secondary-color' unless article.body.to_plain_text.length < 120
  end

  def print_article_errors(article)
    if article.errors.any?
      'shared/error_message'
    else
      'shared/empty'
    end
  end

  def print_user_errors(user)
    if user.errors.any?
      'shared/user_errors'
    else
      'shared/empty'
    end
  end

  def display_image(article)
    condition = article&.image&.attached? &&
                article.image.attachment.blob.present? && article.image.attachment.blob.persisted?

    image_tag article.image, class: 'img-fluid' if condition
  end

  def display_most_popular_title(article)
    link_to article.title, article, class: 'secondary-color' if article
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<article class='article bg-light m-1 '>
  <figure class= ''>
    <%= link_to article do %>
      <%= display_image(article)%>
    <% end %>
  </figure>
  <div class='bg-light px-3 py-1'>
    <h5 class='secondary-color'><%= @category.name if @category %></h5>
    <h6><%= article.title %></h6>
    <p><%= truncate_or_not(article) %></p>
    <p>
      <span><%= continue_reading(article) %></span>
      <span class =" ml-5 secondary-color"><%= pluralize(article.votes.count, 'vote')+'!'%></span>
    </p> 
    <div class='d-flex justify-content-between pb-0 pt-1'>
    <span class ='h6 mt-2'>Author:</span>
      <span class ='h6 ml-n5 m-auto'>
        <%= article.author.name.downcase.capitalize %>
      </span>
      <span ><%= upvote_or_downvote(article) %></span>
    </div>
  </div>
  
</article>

app/views/articles/_form.html.erb
<div class="d-flex justify-content-center my-5">
  <div class="col-4">
    <%= form_for @article do |f| %>
      <div class="row my-2">
        <%= render print_article_errors(@article) %>
      </div> 
      <div class="form-group">
        <%= f.label :title, class:'form-label mb-1' %>
        <%= f.text_field :title, class:'form-control mb-1', placeholder: 'title' %>
        <%= f.label :body, class:'form-label mb-1' %>
        <%= f.text_area :body, class:'form-control mb-1', placeholder: 'Write about your culture',cols: 30, rows: 7 %>
      </div>
      <div class="field form-group">
        <%= f.label :image , 'Add article cover image', class: 'form-label'%>
        <%= f.file_field :image %>
      </div>

      <div class="form-group mt-2 ">
        <%= f.label :categories, 'Add Article Categories', class: 'form-label'%>
        <div>
          <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |b| %>
            <%= b.label class:"form-check-label mx-1" do%>
            <%=b.check_box + "  " + b.text%>
            <%end%>
          <% end %>
        </div>
      </div>

      <%= f.fields_for :categories do |c| %>
        <div class="form-group">
          <%= c.label :name  %>
          <%= c.text_field :name, placeholder: 'add a category', class:'form-control' %>
        </div>      
      <% end %>

      <div class="form-group">
        <%= f.submit class:'btn btn-success mt-1' %>
      </div>
    <% end %>
    
  </div>
</div>
<%= render 'shared/footer' %>

app/views/articles/index.html.erb
<div class="home color-bg">
  <article class="most_popular">
    <%= link_to @most_popular do %>
      <%= display_image(@most_popular) %>
    <% end %>  
    <h4>All About Diverse Cultures in One Place</h4>
    <h5><%= display_most_popular_title(@most_popular) %></h5>
  </article>
  <section class="categories">
    <% @category_article.each do |array| %>
      <article class="category_article">
        <%= link_to array[0] do %>
          <%= display_image(array[1]) %>
        <% end %>
        <h5><%= link_to array[0].name, array[0], class: 'secondary-color' %></h5>
        <h6><%= display_most_popular_title(array[1]) %></h6> 
      </article>
    <% end %>
  </section>
</div>

app/views/articles/new.html.erb
<%= render 'form' %>

app/views/articles/new_html.erb
<%= render 'form' %>

app/views/articles/show.html.erb
<div class='article_page text-light color-bg px-3 pt-3'>
  <article class=''>
    <figure class='w-25 float-start'>
      <%= display_image(@article) %>   
    </figure>
    <div class=' article_details'>
      <h6>
        <span><%= @article.title %></span>
        <span class =" ml-5 secondary-color"><%= pluralize(@article.votes.count, 'vote')+'!'%></span>
       
      </h6>
     
      </p><%= @article.body %><p>
      
    </div>
    <p><span class ='h4'>Author:</span>
        <span class ='h4 ml-2'>
          <%= @article.author.name.downcase.capitalize %>
        </span>
        <span class = 'ml-5'><%= upvote_or_downvote(@article) %></span>
    </p> 
  </article>
</div>
<%= render 'shared/footer' %>

app/views/categories/show.html.erb
  <section class="section_for_articles color-bg p-3">
    <div class="articles mb-3 pt-1">
      <%= render @articles %>
    </div>
  </section>
  <%= render 'shared/footer' %>

app/views/layouts/_signed_in_details.html.erb
<li class="nav-link"><%=link_to current_user.name.capitalize, current_user %></li>
<li class="nav-link"><%= link_to 'LOG OUT', session_path('active'), method: :delete %> </li>
 

app/views/layouts/_signed_out_details.html.erb
<li class="nav-link"><%=link_to 'SIGN UP', new_user_path %></li>
<li class="nav-link"><%= link_to 'LOG IN', new_session_path %> </li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CultureEducate</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid remove-padding ">
      <header>
        <%= render 'shared/navbar' %>
      </header>
      <%= render flash_alert() %>
      <%= render flash_notice() %>
      <%= yield %>
      
    </div>
  </body>
</html>

app/views/shared/_alert.html.erb
<div class='container-fluid'>
  <p class="row bg-danger mb-0"> <%=alert %> </p>
</div>

app/views/shared/_error_message.html.erb
<% @article.errors.full_messages.each do |msg| %>
  <li class='text-danger'>
  <%=msg %>
  </li>
<%end %>

app/views/shared/_footer.html.erb
<footer class='px-3 mt-2'>

  <p class='my-auto'>
    <%= link_to 'CultureEducate', root_path, class: 'my-auto text-white' %>
  </p>

  <ul class="d-none d-md-flex my-auto">
    <%= link_to root_path do %>
      <li class="link secondary-color mx-1">Privacy</li>
    <% end %>
    <%= link_to root_path  do %>
      <li class="link secondary-color mx-1"> Licence</li>
    <% end %>
      <li class=" text-white mx-1">Copyright 2014</li>
      <li class="text-white mx-1">All rights reserved.</li>
  </ul>
  <ul class="d-flex my-auto">
    <li class='text-white' >Contact </li>
    <%= link_to 'https://github.com/wandji20'  do %>
      <li class="link icon "><i class="fa fa-github" aria-hidden="true"></i></li>
      
    <% end %>
    <%= link_to 'https://twitter.com/wandjibertrand'  do %>
      <li class="link icon"> <i class="fa fa-twitter" aria-hidden="true"></i></li>
    
    <% end %>
    <%= link_to 'https://www.linkedin.com/in/wandji-bertrand/'  do %>
    <li class="link icon"><i class="fa fa-linkedin" aria-hidden="true"> </li></i>
    <% end %>
  </ul>

</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar bg-light">
  <%= link_to root_path class: "col-sm-3" do %>
    <h5>CultureEducate</h5>
  <% end %>

  <ul class="navbar-nav">
    <%= link_to new_article_path do %>
      <li class="nav-link">NEW ARTICLE</li>
    <% end %>
  </ul>
  <ul class="navbar-nav">
    <%= render signed_in_details() %>
    <%= render signed_out_details() %>
  </ul>
</nav>

app/views/shared/_notice.html.erb
<div class='container-fluid'>
  <p class="row bg-success justify-content-center mb-0"> <%=notice %> </p>
</div>

app/views/shared/_user_errors.html.erb
<% @user.errors.full_messages.each do |msg| %>
  <li class='text-danger'>
  <%=msg %>
  </li>
<%end %>

app/views/users/_sign_up.html.erb
<div class = 'd-flex justify-content-center mt-5'>
  <div class="col-sm-8 col-md-5 mt-5 ">
    <%= form_for @user do |f|%>
      <div class="row my-2">
        <%= render print_user_errors(@user) %>
      </div> 
      <%= f.label :name, 'Name', class: 'form-label mb-2' %>
      <%= f.text_field :name, placeholder: 'Input name', class:'form-control mb-2'%>
      <%= f.submit 'Sign Up', class: 'btn btn-success' %>
    <% end %>
  </div>
</div>
<%= render 'shared/footer' %>

app/views/users/new.html.erb
<%= render 'sign_up' %>
<%= render 'shared/footer' %>

app/views/users/show.html.erb
<section class='section_for_articles color-bg'>
  <h3 class="row pt-3 justify-content-center secondary-color ">AUTHORED ARTICLES</h3>
  <div class="articles my-3">
    <%= render @authored_articles %>
  </div>
</section>
<%= render 'shared/footer' %>